package completion

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// AliasCompletion holds custom fish completions for an aliased command.
type AliasCompletion struct {
	Alias string
	Lines string
}

var extraCompletions []AliasCompletion
var lazyGenerators []func() string
var lazyAliasGenerators []func() string

// RegisterAlias registers extra fish completion lines for a command alias.
// Use this for modules with custom completions (e.g., zl, mcp).
func RegisterAlias(alias string, lines string) {
	extraCompletions = append(extraCompletions, AliasCompletion{Alias: alias, Lines: lines})
}

// RegisterLazy registers a function that generates completion lines at build time.
// Use this for completions that depend on all modules being registered first.
func RegisterLazy(fn func() string) {
	lazyGenerators = append(lazyGenerators, fn)
}

// RegisterLazyAliases registers a function that generates fish `alias` definition
// lines (runnable command aliases) at build time. These are written to the
// fish conf.d directory so they load at every shell startup, unlike completion
// files which fish only autoloads lazily when completion is first requested.
func RegisterLazyAliases(fn func() string) {
	lazyAliasGenerators = append(lazyAliasGenerators, fn)
}

// BuildAliasDefinitions returns the combined `alias` definition lines (with a
// header). These are meant for a startup-sourced file (fish conf.d), so the
// aliases exist as runnable commands in every interactive shell.
func BuildAliasDefinitions() string {
	if len(lazyAliasGenerators) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("# cly aliases — autoloaded at every shell startup (fish sources conf.d/*.fish).\n")
	b.WriteString("# Generated by `cly completion fish install`. Do not edit by hand.\n")
	for _, fn := range lazyAliasGenerators {
		b.WriteString(fn())
	}
	return b.String()
}

// RegisteredAliases returns the names of aliases with custom completions.
func RegisteredAliases() []string {
	names := make([]string, len(extraCompletions))
	for i, ac := range extraCompletions {
		names[i] = ac.Alias
	}
	return names
}

// BuildExtraCompletions returns the combined extra completion lines.
func BuildExtraCompletions() string {
	if len(extraCompletions) == 0 && len(lazyGenerators) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("\n# Alias completions\n")
	for _, ac := range extraCompletions {
		b.WriteString(ac.Lines)
		if !strings.HasSuffix(ac.Lines, "\n") {
			b.WriteString("\n")
		}
	}
	for _, fn := range lazyGenerators {
		b.WriteString(fn())
	}
	return b.String()
}

func Register(parent *cobra.Command) {
	parent.CompletionOptions.DisableDefaultCmd = true

	fishCmd := &cobra.Command{
		Use:   "fish",
		Short: "Generate fish completions",
		RunE: func(cmd *cobra.Command, args []string) error {
			cache, _ := cmd.Flags().GetBool("cache")
			if cache {
				return cacheFish(parent)
			}
			return genFish(parent, cmd.OutOrStdout())
		},
	}
	fishCmd.Flags().Bool("cache", false, "Write to cache file (~/.cache/fish_completions/cly.fish); skip if already cached")

	installCmd := &cobra.Command{
		Use:   "install",
		Short: "Install completions (completions/cly.fish) and startup aliases (conf.d/cly-aliases.fish)",
		RunE: func(cmd *cobra.Command, args []string) error {
			dir, _ := cmd.Flags().GetString("dir")
			confDir, _ := cmd.Flags().GetString("conf-d")
			if dir == "" || confDir == "" {
				home, err := os.UserHomeDir()
				if err != nil {
					return err
				}
				if dir == "" {
					dir = filepath.Join(home, ".config", "fish", "completions")
				}
				if confDir == "" {
					confDir = filepath.Join(home, ".config", "fish", "conf.d")
				}
			}
			return installFish(parent, dir, confDir)
		},
	}
	installCmd.Flags().String("dir", "", "Override completions directory")
	installCmd.Flags().String("conf-d", "", "Override fish conf.d directory (startup-sourced aliases)")

	fishCmd.AddCommand(installCmd)

	cmd := &cobra.Command{
		Use:       "completion [fish|bash|zsh]",
		Short:     "Generate shell completions",
		ValidArgs: []string{"fish", "bash", "zsh"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return fmt.Errorf("specify shell: fish, bash, or zsh")
			}
			w := cmd.OutOrStdout()
			switch args[0] {
			case "bash":
				return parent.GenBashCompletion(w)
			case "zsh":
				return parent.GenZshCompletion(w)
			default:
				return fmt.Errorf("unsupported shell: %s (use 'cly completion fish' instead)", args[0])
			}
		},
	}

	cmd.AddCommand(fishCmd)
	parent.AddCommand(cmd)
}

func genFish(root *cobra.Command, w interface{ Write([]byte) (int, error) }) error {
	var buf bytes.Buffer
	if err := root.GenFishCompletion(&buf, true); err != nil {
		return err
	}

	// Keep both alias definitions and completion wrappers in the generated
	// output. This preserves the cached-init startup path
	// (`cly completion fish` -> ~/.cache/fish_completions/cly.fish) that some
	// shell configs source at startup. Note: fish autoloads files in
	// completions/ only lazily, so the install command ALSO writes the alias
	// definitions to conf.d (see installFish) for reliable startup loading.
	buf.WriteString("\n")
	buf.WriteString(BuildAliasDefinitions())
	buf.WriteString(BuildExtraCompletions())

	_, err := w.Write(buf.Bytes())
	return err
}

// CachePath returns the well-known cache file path.
func CachePath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".cache", "fish_completions", "cly.fish"), nil
}

// ClearCache removes the cached completion file.
func ClearCache() error {
	p, err := CachePath()
	if err != nil {
		return err
	}
	if err := os.Remove(p); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

func cacheFish(root *cobra.Command) error {
	p, err := CachePath()
	if err != nil {
		return err
	}

	// Skip if cache already exists
	if _, err := os.Stat(p); err == nil {
		return nil
	}

	if err := os.MkdirAll(filepath.Dir(p), 0755); err != nil {
		return fmt.Errorf("creating cache directory: %w", err)
	}

	var buf bytes.Buffer
	if err := genFish(root, &buf); err != nil {
		return err
	}

	if err := os.WriteFile(p, buf.Bytes(), 0644); err != nil {
		return err
	}

	fmt.Fprintf(os.Stderr, "Cached completions to %s\n", p)
	return nil
}

func installFish(root *cobra.Command, dir, confDir string) error {
	// Clear stale cache so next shell start regenerates it
	ClearCache()

	var buf bytes.Buffer
	if err := genFish(root, &buf); err != nil {
		return err
	}

	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating directory %s: %w", dir, err)
	}

	outPath := filepath.Join(dir, "cly.fish")
	if err := os.WriteFile(outPath, buf.Bytes(), 0644); err != nil {
		return err
	}

	fmt.Fprintf(os.Stderr, "Installed completions to %s\n", outPath)

	// Write alias definitions to conf.d so they are sourced at every shell
	// startup. Files in completions/ are autoloaded lazily by fish (only when
	// a completion for that command is first requested), so alias definitions
	// placed there are NOT available as runnable commands in a fresh shell.
	// conf.d/*.fish is sourced unconditionally at startup.
	if aliasContent := BuildAliasDefinitions(); aliasContent != "" && confDir != "" {
		if err := os.MkdirAll(confDir, 0755); err != nil {
			return fmt.Errorf("creating directory %s: %w", confDir, err)
		}
		aliasPath := filepath.Join(confDir, "cly-aliases.fish")
		if err := os.WriteFile(aliasPath, []byte(aliasContent), 0644); err != nil {
			return err
		}
		fmt.Fprintf(os.Stderr, "Installed startup aliases to %s\n", aliasPath)
	}

	return nil
}
