# Build stage
FROM 492684252576.dkr.ecr.us-east-1.amazonaws.com/golang:1.25 AS build
WORKDIR /app
ARG GHA_PAT
ARG RIVER_PRO_SECRET
RUN mkdir -p /app/bin

ENV GO111MODULE=on
ENV GOPRIVATE "github.com/NSXBet/*, github.com/nsxbet/*"
ENV RIVER_PRO_SECRET=$RIVER_PRO_SECRET
ENV GOPROXY=https://proxy.golang.org,https://river:$RIVER_PRO_SECRET@riverqueue.com/goproxy,direct
ENV GONOSUMDB=github.com/NSXBet,github.com/nsxbet,riverqueue.com/riverpro
ENV GHA_PAT=$GHA_PAT
ENV VERSION=$VERSION
RUN git config --global url."https://$GHA_PAT@github.com/".insteadOf "https://github.com/"

COPY . .
RUN go mod download all

ENV ROOT_PATH /app
RUN go build -ldflags "-X github.com/NSXBet/{{ .ProjectName }}/infra/version.version=$(git rev-parse --abbrev-ref HEAD)" -o /app/bin/cli ./main.go
RUN chmod +x /app/bin/cli

# Runtime stage
FROM gcr.io/distroless/base-nossl-debian12
WORKDIR /app
COPY --from=build /app/bin/cli /app/cli
COPY ./config /app/config
ENV CONFIG_PATH=/app/config
ENTRYPOINT [ "/app/cli" ]
