include scripts/makefiles/Makefile.defs
include scripts/makefiles/Makefile.format
include scripts/makefiles/Makefile.gen
include scripts/makefiles/Makefile.run
include scripts/makefiles/Makefile.testing
include scripts/makefiles/Makefile.lint