# vim: set ft=make:
.PHONY: all clean test
clean:
	@rm -rf *.out

.PHONY: test
test: unit coverage coverage-package

.PHONY: unit
unit: gotestsum run-unit coverage coverage-package

run-unit:
	@gotestsum --format testdox --junitfile unit.xml -- --short --cover --covermode count --coverprofile coverage.unit.out ./...

.PHONY: update-unit-snapshots
update-unit-snapshots:
	@UPDATE_SNAPSHOTS=true ${MAKE} unit

.PHONY: gotestsum
gotestsum:
	@which gotestsum > /dev/null || (echo "gotestsum not found. Installing..." && go install gotest.tools/gotestsum@latest)

.PHONY: coverage
coverage: merge-coverage
	@go tool cover --func ./coverage.out

.PHONY: coverage-html
coverage-html: merge-coverage
	@go tool cover -html=coverage.out -o coverage.html
	@open coverage.html

.PHONY: merge-coverage
merge-coverage: gocovmerge
	@gocovmerge $(shell find . -type f -name "coverage.*.out") > coverage.out

.PHONY: gocovmerge
gocovmerge:
	@which gocovmerge > /dev/null || (echo "gocovmerge not found. Installing..." && go install go.shabbyrobe.org/gocovmerge/cmd/gocovmerge@latest)

.PHONY: load
load: ghz load-echo

.PHONY: load-echo
load-echo: ghz
	@echo "=========================================="
	@echo "Running load test for the Echo GRPC route:"
	@echo "=========================================="
	@ghz --insecure --async \
		--call nsx.go_grpc_service.v1.GoGRPCServiceService/Echo \
		-c 10 --rps 2000 -n 4000 \
		-d '{"text":"{{.WorkerID}}"}' 0.0.0.0:9090

.PHONY: ghz
ghz:
	@which ghz > /dev/null || (echo "ghz not found. Installing..." && brew install ghz)

.PHONY: coverage-package
coverage-package: merge-coverage coverage-package-setup
	@package-coverage -c ./internal

.PHONY: coverage-package-setup
coverage-package-setup:
	@which package-coverage > /dev/null || (echo "package-coverage not found. Installing..." && go install github.com/corsc/go-tools/package-coverage@v1.3.4)
