package envs

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"charm.land/bubbles/v2/spinner"
	tea "charm.land/bubbletea/v2"
	"charm.land/lipgloss/v2"
)

var (
	titleStyle   = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("#7DD3FC"))
	mutedStyle   = lipgloss.NewStyle().Foreground(lipgloss.Color("#6B7280"))
	successStyle = lipgloss.NewStyle().Foreground(lipgloss.Color("#86EFAC"))
	errorStyle   = lipgloss.NewStyle().Foreground(lipgloss.Color("#FCA5A5"))
)

type resultMsg fetchResult

type model struct {
	ctx       context.Context
	profile   string
	opBinary  string
	tokens    sessions
	cacheFile string
	results   <-chan fetchResult
	total     int
	complete  int
	variables int
	files     int
	logs      []string
	fields    []Field
	spinner   spinner.Model
	err       error
}

func newModel(ctx context.Context, config Config, profile, opBinary, cacheFile string, tokens sessions) model {
	indicator := spinner.New()
	indicator.Style = lipgloss.NewStyle().Foreground(lipgloss.Color("#7DD3FC"))
	return model{
		ctx:       ctx,
		profile:   profile,
		opBinary:  opBinary,
		tokens:    tokens,
		cacheFile: cacheFile,
		results:   fetchAll(ctx, opBinary, config.Secrets, tokens),
		total:     len(config.Secrets),
		spinner:   indicator,
	}
}

func (m model) Init() tea.Cmd {
	return tea.Batch(m.spinner.Tick, waitForResult(m.results))
}

func (m model) Update(message tea.Msg) (tea.Model, tea.Cmd) {
	switch message := message.(type) {
	case tea.KeyPressMsg:
		if message.String() == "ctrl+c" || message.String() == "q" {
			return m, tea.Quit
		}
	case spinner.TickMsg:
		var command tea.Cmd
		m.spinner, command = m.spinner.Update(message)
		return m, command
	case resultMsg:
		m.complete++
		if message.Err != nil {
			m.logs = append(m.logs, errorStyle.Render("✗ ")+message.Secret.Name+mutedStyle.Render("  "+message.Err.Error()))
		} else {
			selected := resolveEval(m.ctx, SelectFields(message.Fields, m.profile))
			m.fields = append(m.fields, selected...)
			m.variables += len(selected)
			files, err := downloadAttachments(m.ctx, m.opBinary, filepath.Dir(m.cacheFile), message.Secret, message.Files, m.tokens)
			if err != nil {
				m.logs = append(m.logs, errorStyle.Render("✗ ")+err.Error())
			}
			m.files += files
			details := fmt.Sprintf("  %d variables", len(selected))
			if files > 0 {
				details += fmt.Sprintf(", %d files", files)
			}
			m.logs = append(m.logs, successStyle.Render("✓ ")+message.Secret.Name+mutedStyle.Render(details))
		}
		if m.complete == m.total {
			if err := writeCache(m.cacheFile, m.fields); err != nil {
				m.err = err
				m.logs = append(m.logs, errorStyle.Render("✗ ")+err.Error())
			} else {
				m.logs = append(m.logs, successStyle.Render("✓ ")+fmt.Sprintf("Loaded %d variables and %d files from %d items", m.variables, m.files, m.total))
			}
			return m, tea.Quit
		}
		return m, waitForResult(m.results)
	}
	return m, nil
}

func (m model) View() tea.View {
	header := titleStyle.Render("1Password environment loader") + "  " + mutedStyle.Render("profile: "+m.profile)
	activity := m.spinner.View() + " " + mutedStyle.Render(fmt.Sprintf("Fetching items in parallel · %d/%d items", m.complete, m.total))
	body := strings.Join(m.logs, "\n")
	if body == "" {
		body = mutedStyle.Render("Waiting for 1Password…")
	}
	return tea.NewView(header + "\n" + activity + "\n\n" + body)
}

func (m *model) runPlain() error {
	for m.complete < m.total {
		result := <-m.results
		m.complete++
		if result.Err != nil {
			fmt.Fprintf(os.Stderr, "✗ %s: %v\n", result.Secret.Name, result.Err)
			continue
		}
		selected := resolveEval(m.ctx, SelectFields(result.Fields, m.profile))
		m.fields = append(m.fields, selected...)
		m.variables += len(selected)
		files, err := downloadAttachments(m.ctx, m.opBinary, filepath.Dir(m.cacheFile), result.Secret, result.Files, m.tokens)
		if err != nil {
			fmt.Fprintf(os.Stderr, "warning: %v\n", err)
		}
		m.files += files
		fmt.Printf("✓ %s  %d variables", result.Secret.Name, len(selected))
		if files > 0 {
			fmt.Printf(", %d files", files)
		}
		fmt.Println()
	}
	if err := writeCache(m.cacheFile, m.fields); err != nil {
		return err
	}
	fmt.Printf("✓ Loaded %d variables and %d files from %d items\n", m.variables, m.files, m.total)
	return nil
}

func waitForResult(results <-chan fetchResult) tea.Cmd {
	return func() tea.Msg { return resultMsg(<-results) }
}

func fishLiteral(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "\\'") + "'"
}

func writeCache(path string, fields []Field) error {
	var content strings.Builder
	content.WriteString("# Generated by cly envs\n")
	for _, field := range fields {
		content.WriteString("set -gx ")
		content.WriteString(field.Label)
		content.WriteByte(' ')
		content.WriteString(fishLiteral(field.Value))
		content.WriteByte('\n')
	}
	if err := os.WriteFile(path, []byte(content.String()), 0o600); err != nil {
		return fmt.Errorf("write cache: %w", err)
	}
	return nil
}
