app:
  name: cly
  debug: false
  version: 0.1.1
theme:
  style: charm # Options: charm | dracula | catppuccin
modules:
  uuid:
    default_version: v4 # Options: v4 | v7
  demo:
    show_count: true
