package gitcommits

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/yurifrl/cly/pkg/llm"
)

// messageResponseWire is the per-group message payload the message LLM returns.
// It reuses RawGroup's fields so one struct covers both request and response.
type messageResponseWire struct {
	Groups []struct {
		ID      int    `json:"id"`
		Title   string `json:"title"`
		Type    string `json:"type,omitempty"`
		Scope   string `json:"scope,omitempty"`
		Summary string `json:"summary,omitempty"`
	} `json:"groups"`
}

const messageSystemPrompt = `You write conventional commit messages for planned commit groups.
You receive numbered groups, each with its files. For EACH group return title, type, scope, summary.
Rules:
- title: conventional format "type(scope): imperative summary", lowercase, no trailing period, <= 72 chars
- type: one of feat, fix, refactor, docs, test, chore, build, ci, style, perf
- scope: short singular noun derived from the area of the files (e.g. ai, planner, executor); empty if truly global
- summary: one sentence explaining WHY the change exists, not what files changed
Respond with ONLY a JSON object: {"groups":[{"id":<the group id>,"title":"...","type":"...","scope":"...","summary":"..."}]}
Every group id must appear exactly once.`

// FillMessages fills each group of a bare plan (e.g. from the jev planner,
// which only groups files) with conventional commit titles generated by the
// normal chat LLM. Groups whose Title is already set are left untouched, so
// chat-planner plans pass through unchanged and revision loops can re-fill
// selectively. Mutates plan in place.
func FillMessages(ctx context.Context, plan *RawPlan, client llm.Client, timeout time.Duration, customPrompt string) error {
	if len(plan.Groups) == 0 {
		return nil
	}
	if timeout == 0 {
		timeout = defaultTimeout
	}

	needs := false
	for _, g := range plan.Groups {
		if strings.TrimSpace(g.Title) == "" {
			needs = true
			break
		}
	}
	if !needs {
		return nil
	}

	msgCtx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()

	var b strings.Builder
	for i, g := range plan.Groups {
		fmt.Fprintf(&b, "GROUP %d\n", i+1)
		if g.Type != "" {
			fmt.Fprintf(&b, "  type hint: %s\n", g.Type)
		}
		if g.Scope != "" {
			fmt.Fprintf(&b, "  scope hint: %s\n", g.Scope)
		}
		for _, it := range g.Items {
			fmt.Fprintf(&b, "  - %s\n", it.File)
		}
	}

	userMsg := fmt.Sprintf("Write messages for these %d groups:\n\n%s", len(plan.Groups), b.String())
	if customPrompt != "" {
		userMsg = fmt.Sprintf("<user_instructions>\n%s\n</user_instructions>\n\n%s", customPrompt, userMsg)
	}

	resp, err := client.Complete(msgCtx, messageSystemPrompt, []llm.Message{
		{Role: llm.RoleUser, Content: userMsg},
	})
	if err != nil {
		return fmt.Errorf("message generation failed: %w", err)
	}

	var wire messageResponseWire
	if err := json.Unmarshal([]byte(stripFences(resp)), &wire); err != nil {
		return fmt.Errorf("invalid message JSON: %w", err)
	}

	for _, wg := range wire.Groups {
		idx := wg.ID - 1
		if idx < 0 || idx >= len(plan.Groups) || strings.TrimSpace(wg.Title) == "" {
			continue
		}
		g := &plan.Groups[idx]
		g.Title = strings.TrimSpace(wg.Title)
		if wg.Type != "" {
			g.Type = wg.Type
		}
		if g.Type == "" {
			g.Type = inferType(g.Title)
		}
		if wg.Scope != "" {
			g.Scope = wg.Scope
		}
		if wg.Summary != "" {
			g.Summary = wg.Summary
		}
	}

	// Any group still untitled gets a deterministic fallback so execution
	// never commits an empty message.
	for i := range plan.Groups {
		g := &plan.Groups[i]
		if strings.TrimSpace(g.Title) != "" {
			continue
		}
		typ := g.Type
		if typ == "" {
			typ = "chore"
		}
		title := typ
		if g.Scope != "" {
			title = fmt.Sprintf("%s(%s): update %s", typ, g.Scope, g.Scope)
		} else {
			title = fmt.Sprintf("%s: update %d file(s)", typ, len(g.Items))
		}
		g.Title = title
	}
	return nil
}
