// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package skin

import (
	"fmt"
	"strings"
)

const (
	// Betdev is a Skin of type Betdev.
	Betdev Skin = iota
	// Betnacional is a Skin of type Betnacional.
	Betnacional
	// Mrjackbets is a Skin of type Mrjackbets.
	Mrjackbets
	// Mundialbet is a Skin of type Mundialbet.
	Mundialbet
)

var ErrInvalidSkin = fmt.Errorf("not a valid Skin, try [%s]", strings.Join(_SkinNames, ", "))

const _SkinName = "betdevbetnacionalmrjackbetsmundialbet"

var _SkinNames = []string{
	_SkinName[0:6],
	_SkinName[6:17],
	_SkinName[17:27],
	_SkinName[27:37],
}

// SkinNames returns a list of possible string values of Skin.
func SkinNames() []string {
	tmp := make([]string, len(_SkinNames))
	copy(tmp, _SkinNames)
	return tmp
}

var _SkinMap = map[Skin]string{
	Betdev:      _SkinName[0:6],
	Betnacional: _SkinName[6:17],
	Mrjackbets:  _SkinName[17:27],
	Mundialbet:  _SkinName[27:37],
}

// String implements the Stringer interface.
func (x Skin) String() string {
	if str, ok := _SkinMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Skin(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Skin) IsValid() bool {
	_, ok := _SkinMap[x]
	return ok
}

var _SkinValue = map[string]Skin{
	_SkinName[0:6]:   Betdev,
	_SkinName[6:17]:  Betnacional,
	_SkinName[17:27]: Mrjackbets,
	_SkinName[27:37]: Mundialbet,
}

// ParseSkin attempts to convert a string to a Skin.
func ParseSkin(name string) (Skin, error) {
	if x, ok := _SkinValue[name]; ok {
		return x, nil
	}
	return Skin(0), fmt.Errorf("%s is %w", name, ErrInvalidSkin)
}

// MarshalText implements the text marshaller method.
func (x Skin) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Skin) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseSkin(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
